### ISSUE TITLE
config_GAN.json ?

### ISSUE THREAD

**Issue by jinzhenmu** [Jakaria08/EESRGAN#8] opened 2020-04-13 08:27 UTC
hi , when i use  python test.py -c config_GAN.json to test 

- error happens 

- EESRGAN/scripts_for_datasets/COWC_EESRGAN_FRCNN_dataset.py", line 32, in __getitem__
    img_path_gt = os.path.join(self.data_dir_gt, self.imgs_gt[idx])

- IndexError: list index out of range

- It is the  config_GAN.jon  problem?

**Comment by Jakaria08** [comment] 2020-04-15 02:13
Duplicate of #7

**Closed** 2020-10-09 13:51 UTC
